name: Docker image - Consumer

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          .dockerignore
          consumer
        ref: master
    - name: Build the Docker image
      run: docker build ./consumer --file ./consumer/Dockerfile --tag consumer:$(date +%s)
